[project]
name = "climate_guard"
version = "0.1.0"
description = "A web scraper for Latvian news articles"
authors = [{ name = "Your Name", email = "your.email@example.com" }]
dependencies = [
    "requests>=2.26.0",
    "beautifulsoup4>=4.10.0",
    "gradio>=4.44.1",
    "openai>=1.51.0",
    "python-dotenv>=1.0.1",
    "anthropic>=0.34.2",
    "ipykernel>=6.29.5",
    "newspaper3k>=0.2.8",
    "lxml[html-clean]>=5.3.0",
    "gdeltdoc>=1.5.0",
    "lxml-html-clean>=0.2.2",
    "jupyter>=1.1.1",
    # Plotting
    "plotly>=5.24.1",
    # Render plotly charts as static figures
    "kaleido>=0.2.1",
    "pyarrow>=18.0.0",
]
requires-python = ">=3.12"

# https://github.com/astral-sh/uv/issues/7703#issuecomment-2376674577
[tool.uv]
constraint-dependencies = ["kaleido!=0.2.1.post1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["climate_guard"]


[tool.black]
line-length = 100
target-version = ['py312']
