[project]
name = "climate_guard"
version = "0.1.0"
description = "A web scraper for Latvian news articles"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "requests>=2.26.0",
    "beautifulsoup4>=4.10.0",
]
requires-python = ">=3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["climate_guard"]


[tool.uv.dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=22.0.0",
    "isort>=5.0.0",
    "flake8>=4.0.0",
]

[tool.black]
line-length = 100
target-version = ['py312']
