services:
  app:
    build: .
    environment:
      LOGLEVEL: INFO
      ENV: docker
      APP_NAME: label-misinformation 
      OPENAI_API_KEY: /run/secrets/openai_key
      MODEL_NAME:  /run/secrets/model_name
      BUCKET_INPUT: mediatree
      BUCKET_OUTPUT: climateguard
      BUCKET_ACCESS: /run/secrets/bucket_access
      BUCKET_SECRET: /run/secrets/bucket_secret
      AWS_DEFAULT_REGION: fr-par
      MIN_MISINFORMATION_SCORE: 10 # the minimum score to have to be kept (10 out of 10)
      DATE: 2025-02-04 # YYYY-MM-DD
      NUMBER_OF_PREVIOUS_DAYS: 7
      # SENTRY_DSN: prod_only
      CHANNEL: europe1 # mediatree former channel name, not title (cnews)
      MEDIATREE_USER : /run/secrets/username_api
      MEDIATREE_PASSWORD: /run/secrets/pwd_api
      MEDIATREE_AUTH_URL: https://keywords.mediatree.fr/api/auth/token/
      KEYWORDS_URL: https://keywords.mediatree.fr/api/export/single # https://keywords.mediatree.fr/api/docs/#/paths/~1api~1export~1single/get
      MODIN_MEMORY: 3000000000
      RAY_COLOR_PREFIX: 1
    secrets:
       - model_name
       - openai_key
       - bucket_access
       - bucket_secret
       - pwd_api
       - username_api
    volumes:
      - ./app:/app/

  label_studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio
    ports:
      - 8080:8080
    environment:
      LOG_LEVEL: DEBUG
    volumes:
      - ./tests:/label-studio/data

  test:
    build: .
    entrypoint: ["pytest", "-vv"]   # use to debug the container if needed ["pytest", "-vv"] 
    environment:
      LOGLEVEL: DEBUG
      ENV: docker
      APP_NAME: label-misinformation 
      OPENAI_API_KEY: /run/secrets/openai_key
      MODEL_NAME:  /run/secrets/model_name
      BUCKET_INPUT: mediatree
      BUCKET_OUTPUT: climateguard
      BUCKET_ACCESS: /run/secrets/bucket_access
      BUCKET_SECRET: /run/secrets/bucket_secret
      AWS_DEFAULT_REGION: fr-par
      MIN_MISINFORMATION_SCORE: 10 # the minimum score to have to be kept (10 out of 10)
      # DATE: 2024-06-01 # YYYY-MM-DD
      # SENTRY_DSN: prod_only
      CHANNEL: itele # mediatree former channel name, not title (cnews)
      MEDIATREE_USER : /run/secrets/username_api
      MEDIATREE_PASSWORD: /run/secrets/pwd_api
      MEDIATREE_AUTH_URL: https://keywords.mediatree.fr/api/auth/token/
      KEYWORDS_URL: https://keywords.mediatree.fr/api/export/single 
    secrets:
       - model_name
       - openai_key
       - bucket_access
       - bucket_secret
       - pwd_api
       - username_api
    volumes:
      - ./app:/app/
      - ./tests:/app/tests

  testconsole:
    build: .
    entrypoint: ["sleep", "12000"]
    environment:
      LOGLEVEL: DEBUG
      ENV: docker
      APP_NAME: label-misinformation 
      OPENAI_API_KEY: /run/secrets/openai_key
      MODEL_NAME:  /run/secrets/model_name
      BUCKET_INPUT: mediatree
      BUCKET_OUTPUT: climateguard
      BUCKET_ACCESS: /run/secrets/bucket_access
      BUCKET_SECRET: /run/secrets/bucket_secret
      AWS_DEFAULT_REGION: fr-par
      MIN_MISINFORMATION_SCORE: 10 # the minimum score to have to be kept (10 out of 10)
      # DATE: 2024-06-01 # YYYY-MM-DD
      # SENTRY_DSN: prod_only
      CHANNEL: itele # mediatree former channel name, not title (cnews)
      MEDIATREE_USER : /run/secrets/username_api
      MEDIATREE_PASSWORD: /run/secrets/pwd_api
      MEDIATREE_AUTH_URL: https://keywords.mediatree.fr/api/auth/token/
      KEYWORDS_URL: https://keywords.mediatree.fr/api/export/single 
    secrets:
       - model_name
       - openai_key
       - bucket_access
       - bucket_secret
       - pwd_api
       - username_api
    volumes:
      - ./app:/app/
      - ./tests:/app/tests

secrets: # https://docs.docker.com/compose/use-secrets/
  openai_key:
    file: secrets/openai_key
  model_name:
    file: secrets/model_name
  bucket_access:
    file: secrets/bucket_access
  bucket_secret:
    file: secrets/bucket_secret
  pwd_api:
    file: secrets/pwd_api.txt
  username_api:
    file: secrets/username_api.txt