"""Generate affirmation/debunk training conversations from parsed PDF sections.

Reads the per-subsection JSONL produced by parse_pdf_to_jsonl.py (chapter_title,
subsection_title, text, ...) and, for each subsection, asks a teacher LLM
(Claude or Mistral) to generate `--n-pairs` short affirmation/debunk pairs
grounded strictly in that subsection's text. Each pair is generated by its
own independent API call, all fired concurrently (bounded by --concurrency) -
not one call asked to produce all --n-pairs pairs at once. This keeps each
response tiny (so it never gets cut off by the token limit, unlike asking
for e.g. 20 pairs in a single completion) and lets pairs for the same
subsection generate in parallel:

- Half are TRUE affirmations: statements the source text supports. Their
  debunk is a short sentence confirming the affirmation.
- Half are FALSE affirmations: statements the source text contradicts (myths,
  exaggerations, or misconceptions the text addresses). Their debunk is a
  short explanation of why it's false, citing facts/figures from the text.

Each pair is written as one two-turn conversation record:
    {"messages": [{"role": "user", "content": affirmation},
                   {"role": "assistant", "content": debunk}],
     "metadata": {"is_true": bool, "chapter_title": ..., "subsection_title": ...,
                  "start_page": ..., "end_page": ..., "source_id": ...}}

Usage:
    python generate_conversations.py <model> [--provider claude|mistral] [--n-pairs N]
        [--input PATH] [--output PATH] [--concurrency N] [--limit N]
        [--overwrite] [--dry-run] [--env-file .env]
"""

import argparse
import asyncio
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from tqdm.asyncio import tqdm as async_tqdm

EXPERT_MODELS_DIR = Path(__file__).resolve().parents[1]

DEFAULT_MODEL = {
    "claude": "claude-sonnet-5",
    "mistral": "mistral-large-latest",
}

SYSTEM_PROMPT = """\
You produce a single training example for a fact-checking assistant, from an \
excerpt of a book that debunks misinformation on its topic using established \
facts, figures and scientific evidence.

Given the excerpt below, generate exactly one {kind} affirmation/debunk pair.

{kind_instructions}

Hard rules:
- Base the affirmation and debunk strictly on the excerpt. Do not invent \
facts that are not in it.
- Write in the same language as the excerpt.
- The affirmation should read like something a person might plausibly say or \
believe, not like a quiz question or a direct quote from the text. Do not mention the excerpt.
- Output ONLY a single JSON object, no prose before or after, no markdown \
code fences, matching this schema exactly:
{{"affirmation": "...", "is_true": {is_true_literal}, "debunk": "..."}}\
"""

TRUE_INSTRUCTIONS = (
    "The affirmation must be a statement the excerpt supports. The debunk is "
    "a short, single-sentence confirmation that the statement is accurate."
)
FALSE_INSTRUCTIONS = (
    "The affirmation must be a statement the excerpt contradicts or "
    "misrepresents - a common myth, exaggeration, or misconception on this "
    "topic. The debunk is a short explanation (2-4 sentences) of why the "
    "affirmation is false, citing concrete facts or figures from the excerpt."
)


def build_system_prompt(is_true: bool) -> str:
    return SYSTEM_PROMPT.format(
        kind="TRUE" if is_true else "FALSE",
        kind_instructions=TRUE_INSTRUCTIONS if is_true else FALSE_INSTRUCTIONS,
        is_true_literal=str(is_true).lower(),
    )


def build_user_message(record: dict[str, Any]) -> str:
    heading = " - ".join(
        part for part in (record.get("chapter_title"), record.get("subsection_title")) if part
    )
    return f"EXCERPT ({heading}):\n{record['text']}"


def extract_json_objects(text: str) -> list[str]:
    """Return substrings for each complete top-level {...} object in text.

    Scans char-by-char (string/escape aware, since regex can't reliably
    balance braces) so a response cut short mid-object - e.g. hitting
    max_tokens - still yields every object that completed before the cut.
    """
    objects = []
    depth = 0
    start = None
    in_string = False
    escape = False
    for i, ch in enumerate(text):
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    objects.append(text[start : i + 1])
                    start = None
    return objects


def parse_single_pair(raw: str) -> dict[str, Any] | None:
    """Parse the teacher's single JSON object response, tolerating markdown
    fences and stray preamble/trailing text around the object."""
    match = re.search(r"\{.*", raw, re.DOTALL)
    if not match:
        return None
    for obj_str in extract_json_objects(match.group(0)):
        try:
            obj = json.loads(obj_str)
        except json.JSONDecodeError:
            continue
        affirmation = str(obj.get("affirmation", "")).strip()
        debunk = str(obj.get("debunk", "")).strip()
        is_true = obj.get("is_true")
        if affirmation and debunk and isinstance(is_true, bool):
            return {"affirmation": affirmation, "is_true": is_true, "debunk": debunk}
    return None


# ── Providers ────────────────────────────────────────────────────────────────


RATE_LIMIT_MAX_RETRIES = 5
RATE_LIMIT_BASE_DELAY = 5  # seconds; doubles each retry, capped below


async def call_claude(client, model: str, system: str, user: str, max_tokens: int) -> str:
    import anthropic

    delay = RATE_LIMIT_BASE_DELAY
    for attempt in range(1, RATE_LIMIT_MAX_RETRIES + 1):
        try:
            response = await client.messages.create(
                model=model,
                max_tokens=max_tokens,
                system=system,
                messages=[{"role": "user", "content": user}],
            )
            return next((block.text for block in response.content if block.type == "text"), "")
        except anthropic.RateLimitError as exc:
            print(
                f"[warn] Claude rate limited (attempt {attempt}/{RATE_LIMIT_MAX_RETRIES}), "
                f"retrying in {delay}s: {exc!r}",
                file=sys.stderr,
            )
            await asyncio.sleep(delay)
            delay = min(delay * 2, 60)
        except anthropic.APIError as exc:
            print(f"[warn] Claude API call failed: {exc!r}", file=sys.stderr)
            return ""
    print(f"[warn] Claude still rate limited after {RATE_LIMIT_MAX_RETRIES} retries, giving up", file=sys.stderr)
    return ""


async def call_mistral(client, model: str, system: str, user: str, max_tokens: int) -> str:
    delay = RATE_LIMIT_BASE_DELAY
    for attempt in range(1, RATE_LIMIT_MAX_RETRIES + 1):
        try:
            response = await client.chat.complete_async(
                model=model,
                max_tokens=max_tokens,
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
            )
            return response.choices[0].message.content or ""
        except Exception as exc:  # mistralai raises several SDK-specific error types
            if getattr(exc, "status_code", None) == 429:
                print(
                    f"[warn] Mistral rate limited (attempt {attempt}/{RATE_LIMIT_MAX_RETRIES}), "
                    f"retrying in {delay}s",
                    file=sys.stderr,
                )
                await asyncio.sleep(delay)
                delay = min(delay * 2, 60)
                continue
            print(f"[warn] Mistral API call failed: {exc!r}", file=sys.stderr)
            return ""
    print(f"[warn] Mistral still rate limited after {RATE_LIMIT_MAX_RETRIES} retries, giving up", file=sys.stderr)
    return ""


def make_client(provider: str):
    if provider == "claude":
        import anthropic

        return anthropic.AsyncAnthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    if provider == "mistral":
        from mistralai.client import Mistral

        return Mistral(api_key=os.environ["MISTRAL_API_KEY"])
    raise ValueError(f"Unknown provider: {provider}")


# ── Generation ───────────────────────────────────────────────────────────────


async def generate_one_pair(
    client,
    provider: str,
    model: str,
    record: dict[str, Any],
    is_true: bool,
    max_tokens: int,
    semaphore: asyncio.Semaphore,
) -> dict[str, Any] | None:
    system = build_system_prompt(is_true)
    user = build_user_message(record)

    async with semaphore:
        call = call_claude if provider == "claude" else call_mistral
        raw = await call(client, model, system, user, max_tokens)

    pair = parse_single_pair(raw)
    if not pair:
        snippet = raw.strip().replace("\n", " ")[:300] or "(empty response)"
        kind = "TRUE" if is_true else "FALSE"
        print(f"[warn] No valid {kind} pair parsed for {record['id']}: {snippet}", file=sys.stderr)
        return None
    pair["is_true"] = is_true  # we asked for this kind explicitly; trust the request over the model
    return pair


async def generate_for_record(
    client,
    provider: str,
    model: str,
    record: dict[str, Any],
    n_pairs: int,
    max_tokens: int,
    semaphore: asyncio.Semaphore,
) -> list[dict[str, Any]]:
    n_true = n_pairs // 2
    n_false = n_pairs - n_true

    tasks = [
        generate_one_pair(client, provider, model, record, is_true, max_tokens, semaphore)
        for is_true in [True] * n_true + [False] * n_false
    ]
    pairs = [pair for pair in await asyncio.gather(*tasks) if pair]

    results = []
    for pair in pairs:
        results.append(
            {
                "messages": [
                    {"role": "user", "content": pair["affirmation"]},
                    {"role": "assistant", "content": pair["debunk"]},
                ],
                "metadata": {
                    "is_true": pair["is_true"],
                    "chapter_title": record.get("chapter_title", ""),
                    "subsection_title": record.get("subsection_title", ""),
                    "start_page": record.get("start_page"),
                    "end_page": record.get("end_page"),
                    "source_id": record["id"],
                },
            }
        )
    return results


def load_records(input_path: Path) -> list[dict[str, Any]]:
    records = []
    with input_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def already_done_ids(output_path: Path) -> set[str]:
    done: set[str] = set()
    if not output_path.exists():
        return done
    with output_path.open(encoding="utf-8") as f:
        for line in f:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            source_id = obj.get("metadata", {}).get("source_id")
            if source_id:
                done.add(source_id)
    return done


async def main(args: argparse.Namespace) -> None:
    model_dir = EXPERT_MODELS_DIR / args.model
    parsed_dir = model_dir / "data" / "parsed"
    conversations_dir = model_dir / "data" / "conversations"

    if args.input:
        input_path = args.input
    else:
        jsonl_files = sorted(parsed_dir.glob("*.jsonl"))
        if not jsonl_files:
            sys.exit(f"No JSONL files found in {parsed_dir}")
        input_path = jsonl_files[0]

    if args.output:
        output_path = args.output
    else:
        conversations_dir.mkdir(parents=True, exist_ok=True)
        output_path = conversations_dir / input_path.name

    records = load_records(input_path)
    if args.limit:
        records = records[: args.limit]

    done = set() if args.overwrite else already_done_ids(output_path)
    if done:
        print(f"Resuming: {len(done)} source records already processed.")
    pending = [r for r in records if r["id"] not in done]
    print(f"Records to process: {len(pending)} / {len(records)}")

    if args.dry_run:
        for record in pending[: args.limit or len(pending)]:
            print(f"[dry-run] would generate {args.n_pairs} pairs for {record['id']}")
        return

    llm_model = args.model_name or DEFAULT_MODEL[args.provider]
    client = make_client(args.provider)
    semaphore = asyncio.Semaphore(args.concurrency)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    mode = "w" if args.overwrite else "a"
    written = 0
    with output_path.open(mode, encoding="utf-8") as out_f:
        tasks = [
            generate_for_record(
                client, args.provider, llm_model, record, args.n_pairs, args.max_tokens, semaphore
            )
            for record in pending
        ]
        for coro in async_tqdm.as_completed(tasks, total=len(tasks), desc=args.model):
            pairs = await coro
            for pair_record in pairs:
                out_f.write(json.dumps(pair_record, ensure_ascii=False) + "\n")
                written += 1
            out_f.flush()

    print(f"Wrote {written} conversation pairs to {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("model", help="Expert model directory name, e.g. 'biodiversity'")
    parser.add_argument(
        "--provider", choices=["claude", "mistral"], default="mistral", help="Teacher LLM provider"
    )
    parser.add_argument(
        "--model-name", default=None, help="Override the provider's default model id"
    )
    parser.add_argument("--n-pairs", type=int, default=4, help="Affirmation/debunk pairs per subsection")
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=2048,
        help="Max output tokens per API call - raise this if responses get cut off (e.g. with a high --n-pairs)",
    )
    parser.add_argument("--input", type=Path, default=None, help="Input JSONL (default: single file in data/parsed)")
    parser.add_argument("--output", type=Path, default=None, help="Output JSONL (default: data/conversations/<name>.jsonl)")
    parser.add_argument("--concurrency", type=int, default=5, help="Max concurrent API calls")
    parser.add_argument("--limit", type=int, default=None, help="Process at most N source records")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite output instead of resuming")
    parser.add_argument("--dry-run", action="store_true", help="List what would be processed without calling the API")
    parser.add_argument("--env-file", default=".env", help="Path to .env file (default: .env)")
    args = parser.parse_args()

    env_path = Path(args.env_file)
    if env_path.exists():
        load_dotenv(env_path)
    else:
        load_dotenv()

    key_var = "ANTHROPIC_API_KEY" if args.provider == "claude" else "MISTRAL_API_KEY"
    if not args.dry_run and key_var not in os.environ:
        sys.exit(f"Error: {key_var} not set. Add it to your .env file or environment.")

    asyncio.run(main(args))
