name: Test

on:
  push:
    paths:
      - 'jobs/label_misinformation/**'
      - '.github/workflows/test-label-misinformation.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: pytest
      working-directory: jobs/label_misinformation
      run: |
        docker compose up test -d
        docker compose exec test pytest