name: Build & Deploy to Scaleway

on:
  push:
    paths:
      - 'jobs/label_misinformation/**'
      - .github/workflows/deploy-label-misinformation.yml
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

jobs:

  test:
    runs-on: ubuntu-latest
    outputs:
      PROJECT_VERSION: ${{ steps.get_version.outputs.PROJECT_VERSION }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      working-directory: jobs/label_misinformation
      run: pip install -r requirements.txt

    - name: Bump version (patch)
      working-directory: jobs/label_misinformation
      run: |
        pytest